package com.karrar.movieapp.domain.enums

enum class AllMediaType {
    ON_THE_AIR,
    AIRING_TODAY,
    LATEST,
    POPULAR,
    TOP_RATED,
    TRENDING,
    RECENTLY_RELEASED,

    LASTEST_SEASONS,
    BEHIND_THE_SCENES,
    YOU_MIGHT_ALSO_LIKE_SERIES,
    YOU_MIGHT_ALSO_LIKE_MOVIES,
    TOP_REVIEWS_SERIES,
    TOP_REVIEWS_MOVIES,

    UPCOMING,
    MYSTERY,
    ADVENTURE,
    ACTOR_MOVIES,
    LATE_NIGHT_THRILLS,
    MIND_BENDING_STORIES,
    CINEMATIC_MASTERPIECES,
    FAMILY_NIGHT_PICKS,
    BASED_ON_TRUE_EVENTS,
    FEEL_GOOD_FAVORITES,
    MATCHES_YOUR_VIBE,
    RECENTLY_VIEWED,
    YOUR_COLLECTIONS
}