on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Create google-services.json
        run: |
          mkdir -p app
          cat > app/google-services.json << 'EOF'
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Create local.properties
        run: |
          echo "apiKey=\"${{ secrets.API_KEY }}\"" >> local.properties

      - name: Grant gradlew permissions execution
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MovieApp APK
          path: app/build/outputs/apk/debug/app-debug.apk
